[package]
name = "tamagotchi-battle-io"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
gstd.workspace = true
gmeta.workspace = true
store-io.workspace = true
tamagotchi-utils-io.workspace = true
