[package]
name = "escrow-io"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gstd.workspace = true
gmeta.workspace = true
