[package]
name = "tamagotchi-utils-io"
version.workspace = true
edition.workspace = true
publish.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
store-io.workspace = true
gmeta.workspace = true
gstd.workspace = true